from __future__ import annotations

"""JIRA integration — builds payload, creates ticket via Atlassian REST API, records link."""

import logging
from typing import Optional, Dict, Any
from uuid import UUID

import httpx
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.config import get_settings
from app.models.run import Run
from app.models.artifact import Artifact
from app.models.jira_link import JiraLink
from app.services import workflow_service

logger = logging.getLogger(__name__)

CLASSIFICATION_TO_ISSUE_TYPE = {
    "feature_request": "Task",
    "cri": "Task",
    "bug": "Task",
    "production_bug": "Task",
}

PRIORITY_MAP = {
    "high": "Highest",
    "medium": "Medium",
    "low": "Low",
}


def _build_description(verified: dict, agent2: dict) -> str:
    """Build a JIRA-wiki-markup description (REST API v2 format)."""
    lines = []

    # ── Summary panel ──────────────────────────────────────────────
    cl      = agent2.get("classification", "N/A").replace("_", " ").title()
    pri     = agent2.get("priority", "N/A").title()
    score   = agent2.get("priority_score", 0)
    team    = agent2.get("owner_team_suggestion", "Unassigned")
    lines += [
        "{panel:title=Ticket Summary|borderStyle=solid|borderColor=#FF3300|titleBGColor=#FFF1ED|bgColor=#FFFFFF}",
        f"|| Classification || {cl} ||",
        f"|| Priority       || {pri} (score: {score:.1f}) ||",
        f"|| Owning Team    || {team} ||",
        "{panel}",
        "",
    ]

    # ── Problem Statement ──────────────────────────────────────────
    problem = verified.get("problem_statement", "")
    if problem:
        lines += [
            "h2. Problem Statement",
            problem,
            "",
        ]

    # ── Requirements ───────────────────────────────────────────────
    reqs = verified.get("requirements", [])
    if reqs:
        lines.append("h2. Requirements")
        for r in reqs:
            lines.append(f"* {r.get('text', '')}")
        lines.append("")

    # ── Acceptance Criteria ────────────────────────────────────────
    criteria = verified.get("acceptance_criteria", [])
    if criteria:
        lines.append("h2. Acceptance Criteria")
        for ac in criteria:
            lines.append(f"* {ac.get('text', '')}")
        lines.append("")

    # ── Impact ─────────────────────────────────────────────────────
    impact = verified.get("impact", {})
    sev    = impact.get("severity_hint", "")
    who    = impact.get("who_is_affected", "")
    if sev or who:
        lines.append("h2. Impact")
        if sev:
            lines.append(f"* *Severity:* {sev}")
        if who:
            lines.append(f"* *Affected:* {who}")
        lines.append("")

    # ── Product Areas ──────────────────────────────────────────────
    areas = verified.get("related_product_areas", [])
    if areas:
        names = ", ".join(a.get("name", "") for a in areas if a.get("name"))
        lines += [
            "h2. Product Areas",
            names,
            "",
        ]

    # ── Rationale ─────────────────────────────────────────────────
    rationale = agent2.get("rationale", "")
    if rationale:
        lines += [
            "h2. Classification Rationale",
            rationale,
            "",
        ]

    # ── Assumptions ───────────────────────────────────────────────
    assumptions = agent2.get("assumptions", [])
    if assumptions:
        lines.append("h2. Assumptions")
        for a in assumptions:
            lines.append(f"* {a}")
        lines.append("")

    # ── KB Notes ───────────────────────────────────────────────────
    kb = verified.get("kb_validation", {})
    if kb.get("notes"):
        lines += [
            "h2. KB / Support Notes",
            kb["notes"],
            "",
        ]

    # ── Footer ─────────────────────────────────────────────────────
    lines += [
        "----",
        "_Auto-generated by the Chargebee CRI / Feature Request Workflow_",
    ]

    return "\n".join(lines)


class JiraCredentialsMissing(Exception):
    """Raised when Atlassian credentials are not configured — run stays in creating_jira."""


async def _create_jira_via_rest(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Call the Atlassian REST API v2 to create a JIRA issue.

    Returns {"key": "SNAPP-X", "url": "https://...browse/SNAPP-X"} on success.
    Raises JiraCredentialsMissing when credentials are absent (non-fatal).
    """
    settings = get_settings()
    site_url = settings.atlassian_site_url.rstrip("/")
    email = settings.atlassian_email
    token = settings.atlassian_api_token

    if not email or not token:
        raise JiraCredentialsMissing(
            "ATLASSIAN_EMAIL and ATLASSIAN_API_TOKEN not configured — "
            "add them to backend/.env and retry."
        )

    api_url = f"{site_url}/rest/api/2/issue"

    body = {
        "fields": {
            "project": {"key": payload["projectKey"]},
            "issuetype": {"name": payload["issueTypeName"]},
            "summary": payload["summary"],
            "description": payload.get("description", ""),
            "priority": payload.get("additional_fields", {}).get("priority", {"name": "Medium"}),
            "labels": payload.get("additional_fields", {}).get("labels", []),
        }
    }

    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(
            api_url,
            json=body,
            auth=(email, token),
            headers={"Accept": "application/json"},
        )

    if resp.status_code not in (200, 201):
        logger.error("JIRA REST API error %s: %s", resp.status_code, resp.text)
        raise RuntimeError(f"JIRA API {resp.status_code}: {resp.text}")

    data = resp.json()
    jira_key = data["key"]
    jira_url = f"{site_url}/browse/{jira_key}"
    logger.info("JIRA ticket created via REST API: %s", jira_key)
    return {"key": jira_key, "url": jira_url}


async def prepare_and_create_jira(db: AsyncSession, run_id: UUID) -> Dict[str, Any]:
    """Build the JIRA payload, create the ticket via REST API, and record it.

    This is the full end-to-end flow called after PM approval.
    """
    existing = await db.execute(select(JiraLink).where(JiraLink.run_id == run_id))
    link = existing.scalar_one_or_none()
    if link:
        logger.info("JIRA already created for run %s: %s", run_id, link.jira_key)
        return {"already_created": True, "jira_key": link.jira_key, "jira_url": link.jira_url}

    result = await db.execute(
        select(Run).where(Run.id == run_id).options(
            selectinload(Run.artifacts),
            selectinload(Run.document),
        )
    )
    run = result.scalar_one_or_none()
    if not run:
        raise ValueError(f"Run {run_id} not found")

    pm_artifacts = sorted(
        [a for a in run.artifacts if a.stage == "pm_verified"],
        key=lambda a: a.version, reverse=True,
    )
    verified_artifacts = sorted(
        [a for a in run.artifacts if a.stage == "verified_v1"],
        key=lambda a: a.version, reverse=True,
    )

    agent2_payload = pm_artifacts[0].json_payload if pm_artifacts else {}
    verified_payload = verified_artifacts[0].json_payload if verified_artifacts else {}

    classification = agent2_payload.get("classification", "feature_request")
    priority = agent2_payload.get("priority", "medium")
    title = verified_payload.get("title", f"Request from run {run_id}")
    team = agent2_payload.get("owner_team_suggestion", "")

    issue_type = CLASSIFICATION_TO_ISSUE_TYPE.get(classification, "Task")
    jira_priority = PRIORITY_MAP.get(priority, "Medium")
    description = _build_description(verified_payload, agent2_payload)

    labels = [classification]
    if classification == "production_bug":
        labels.append("production")

    settings = get_settings()
    project_key = settings.jira_project_key

    payload = {
        "cloudId": settings.atlassian_cloud_id,
        "projectKey": project_key,
        "summary": title,
        "issueTypeName": issue_type,
        "description": description,
        "contentFormat": "markdown",
        "additional_fields": {
            "priority": {"name": jira_priority},
            "labels": labels,
        },
        "_meta": {
            "classification": classification,
            "priority": priority,
            "team": team,
            "run_id": str(run_id),
            "document_filename": run.document.filename if run.document else None,
        },
    }

    # Save payload artifact
    max_ver = await db.execute(
        select(func.coalesce(func.max(Artifact.version), 0))
        .where(Artifact.run_id == run_id)
    )
    next_version = max_ver.scalar() + 1

    artifact = Artifact(
        run_id=run_id,
        version=next_version,
        stage="jira_payload",
        json_payload=payload,
        created_by="system",
    )
    db.add(artifact)
    await db.commit()
    logger.info("JIRA payload saved for run %s", run_id)

    # Create the ticket via Atlassian REST API
    try:
        jira_result = await _create_jira_via_rest(payload)
    except JiraCredentialsMissing as e:
        logger.warning("JIRA credentials missing for run %s — staying in creating_jira. %s", run_id, e)
        return {"pending": True, "reason": str(e), "run_id": str(run_id)}

    # Record the ticket and transition to done
    jira_link = JiraLink(
        run_id=run_id,
        jira_key=jira_result["key"],
        jira_url=jira_result["url"],
    )
    db.add(jira_link)

    run = await workflow_service.get_run(db, run_id)
    if run and run.status == "creating_jira":
        await workflow_service.transition(db, run, "jira_created")

    logger.info("JIRA %s created and recorded for run %s", jira_result["key"], run_id)
    return {
        "jira_key": jira_result["key"],
        "jira_url": jira_result["url"],
        "run_id": str(run_id),
    }


async def record_jira_ticket(
    db: AsyncSession, run_id: UUID, jira_key: str, jira_url: Optional[str] = None
) -> JiraLink:
    """Record a JIRA ticket that was created externally (fallback/manual path)."""
    existing = await db.execute(select(JiraLink).where(JiraLink.run_id == run_id))
    link = existing.scalar_one_or_none()
    if link:
        logger.info("JIRA already recorded for run %s: %s", run_id, link.jira_key)
        return link

    link = JiraLink(run_id=run_id, jira_key=jira_key, jira_url=jira_url or "")
    db.add(link)

    run = await workflow_service.get_run(db, run_id)
    if run and run.status == "creating_jira":
        await workflow_service.transition(db, run, "jira_created")

    logger.info("JIRA recorded for run %s: %s", run_id, jira_key)
    return link
