from __future__ import annotations

"""RCA Service — generates Root Cause Analysis via LLM and posts it as a JIRA comment."""

import logging
from typing import Optional

import httpx

from app.config import get_settings
from app.agents.llm_client import LLMClient

logger = logging.getLogger(__name__)


_RCA_PROMPT = """You are a senior software engineer writing a Root Cause Analysis for a Chargebee issue.

RULES:
- Be extremely brief and precise. No fluff, no repetition.
- Each section: 1-2 sentences or 2-3 bullet points MAX.
- Use plain technical language a developer can act on.
- Use JIRA wiki markup (h3. headers, * bullets, *bold*). NO markdown.

Issue Data:
- Type: {classification} | Priority: {priority}
- Problem: {problem}
- Requirements: {requirements}
- Severity: {severity} | Affected: {affected}
- Product Areas: {product_areas}
- Analysis: {rationale}

Write EXACTLY this structure:

h3. Root Cause
One sentence explaining the technical root cause.

h3. Impact
* Who is affected and severity (one line)

h3. Fix
* Concrete technical steps to resolve (2-3 bullets max)

h3. Prevention
* One actionable prevention measure
"""


async def generate_rca(verified: dict, agent2: dict) -> str:
    """Use LLM to generate a Root Cause Analysis from the issue data."""
    reqs = verified.get("requirements", [])
    req_text = "; ".join(r.get("text", "") for r in reqs) if reqs else "N/A"

    areas = verified.get("related_product_areas", [])
    area_names = ", ".join(a.get("name", "") for a in areas) if areas else "N/A"

    impact = verified.get("impact", {})

    prompt = _RCA_PROMPT.format(
        classification=agent2.get("classification", "N/A"),
        priority=agent2.get("priority", "N/A"),
        problem=verified.get("problem_statement", "N/A"),
        requirements=req_text,
        severity=impact.get("severity_hint", "N/A"),
        affected=impact.get("who_is_affected", "N/A"),
        product_areas=area_names,
        rationale=agent2.get("rationale", "N/A"),
    )

    client = LLMClient()
    rca_text = await client.generate_text(prompt)

    header = (
        "h2. Root Cause Analysis\n"
        "_(Auto-generated by Chargebee CRI Workflow — Agent-3)_\n"
        "----\n"
    )
    return header + rca_text


async def post_jira_comment(jira_key: str, comment_body: str) -> bool:
    """Post a comment to a JIRA issue via Atlassian REST API v2."""
    settings = get_settings()
    site_url = settings.atlassian_site_url.rstrip("/")
    email = settings.atlassian_email
    token = settings.atlassian_api_token

    if not email or not token or not site_url:
        logger.warning("Atlassian credentials not configured — skipping JIRA comment.")
        return False

    url = f"{site_url}/rest/api/2/issue/{jira_key}/comment"
    body = {"body": comment_body}

    async with httpx.AsyncClient(timeout=30) as client:
        resp = await client.post(
            url,
            json=body,
            auth=(email, token),
            headers={"Accept": "application/json", "Content-Type": "application/json"},
        )

    if resp.status_code not in (200, 201):
        logger.error("JIRA comment failed %s: %s", resp.status_code, resp.text[:200])
        return False

    logger.info("RCA comment posted to %s", jira_key)
    return True


async def generate_and_post_rca(jira_key: str, verified: dict, agent2: dict) -> Optional[str]:
    """Full flow: generate RCA with LLM, post as JIRA comment. Returns the RCA text."""
    try:
        rca = await generate_rca(verified, agent2)
        await post_jira_comment(jira_key, rca)
        logger.info("RCA generated and posted for %s", jira_key)
        return rca
    except Exception as e:
        logger.error("RCA flow failed for %s: %s", jira_key, e)
        return None
